[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/privacy"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy/"
  to = "/index.html"
  status = 200
  force = true
