[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "VITE_API_URL=$VITE_API_URL npm run build"

[build.environment]
  VITE_API_URL = "https://notypeaiweb-backend.onrender.com"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

