[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

